### ISSUE TITLE
Format proposal

### ISSUE THREAD

**Issue by jemus42** [fenhl/kapuzidb#1]
In my opinion, the most important, and thereby most obvious pieces of information would be a track's name, it's date of publication, and the url to it's original post, i.e. a soundcloud url. 

Additional fields could be a list of artists/songs included in the mixtape, as per KapUzi's own accompanying blogpost.

```
[  
   {  
      "name":"name",
      "date":"date (UTC/ISO)",
      "url":"url to soundcloud"
   }
]
```

**Comment by fenhl** [comment]
Do we have information about the time of day when mixtapes were published? Otherwise I would rather leave off the time altogether and have it as a YYYY-MM-DD field.

**Comment by jemus42** [comment]
Good point. I just realized Soundcloud shows the date of publication relatively (e.g. '1 year ago'), which doesn't seem to help either. Apparently we need to get the publication dates from [the blog](http://kapuzi.blogspot.de/), I guess.

**Comment by fenhl** [comment]
Maybe we should just use separate date and time fields.

**Comment by jemus42** [comment]
Possible, yeah. However, since I don't see where we could even get time information, I think a simple %F timestamp would be sufficient either way.

Another field that might be useful: Duration.  
Just in case someone wants to, I don't know, find out which mixtape fits in a regular audio CD.
